server.port=11702
server.host=localhost

spring.jpa.database=POSTGRESQL
spring.datasource.platform=postgres
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
spring.jpa.hibernate.use-new-pk-generator-mappings=true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults = false
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.database.driverClassName=org.postgresql.Driver
spring.datasource.username=uttu
spring.datasource.password=uttu
spring.datasource.url=jdbc:postgresql://localhost:5470/uttu

spring.flyway.enabled=true
organisation.registry.url=http://0.0.0.0/api-proxy/api/organisations/1.0/
providers.registry.url=http://0.0.0.0/api-proxy/api/providers/1.0/



spring.cloud.gcp.project-id=default
spring.cloud.gcp.pubsub.emulatorHost=localhost:8088

orgregister.oauth2.client.audience=toto
spring.flyway.user=uttu
spring.flyway.password=uttu
spring.flyway.url=jdbc:postgresql://localhost:5470/uttu

management.endpoints.web.exposure.include=*

keycloak.auth-server-url=fakeRL
keycloak.realm=fakeREALM
iam.keycloak.client.secret=fakeSecret
keycloak.resource=uttu
stopplace.registry.url=http://0.0.0.0/api-proxy/api/stop_places/1.0/
network.registry.url=http://0.0.0.0/api-proxy/api/offre/1.0/exploitation/reseau/networkAndAuthorities
companies.registry.url=http://0.0.0.0/api-proxy/api/offre/1.0/companies/companiesWithNetexIds





